site_name: Telmi Wiki
repo_name: heuzef/telmi-wiki
copyright: Telmi Interactive

nav:
    - âœ¨ Accueil: index.md
    - ğŸ³ï¸ International: 
      - Stores internationaux : international/stores_internationaux.md
      - CrÃ©er un store international: international/creer_un_store_international.md
    - ğŸ›ï¸ Achats :
      - Miyoo Mini Plus : achats/miyoo_mini_plus.md
      - Carte SD : achats/carte_sd.md

theme:
  name: dracula
  logo: assets/img/telmi-wiki.png
  favicon: assets/img/favicon.ico